package utils

import (
	"errors"
	"regexp"
)

func ConvertIDtoString(objectID string) (string, error) {
	// regex of the primitive object generated by the mongo driver
	re := regexp.MustCompile(`"([^"]*)"`)
	matches := re.FindStringSubmatch(objectID)
	if len(matches) < 1 {
		return "", errors.New("invalid id")
	}
	return matches[1], nil

}
