definitions:
  dto.EventDto:
    properties:
      dateTime:
        type: string
      description:
        type: string
      id:
        type: string
      location:
        type: string
      name:
        type: string
    type: object
  models.Event:
    properties:
      dateTime:
        type: string
      description:
        type: string
      id:
        type: string
      location:
        type: string
      name:
        type: string
      userID:
        type: string
    required:
    - dateTime
    - location
    - name
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
host: localhost:8080
info:
  contact:
    email: siddhant.sonar@hp.com
    name: Siddhant
  description: This is a event management application
  title: Plan My Event API
  version: "1.0"
paths:
  /events:
    get:
      description: Displays all the events present in the app
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.EventDto'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get all events
      tags:
      - events
    post:
      description: Create a new event
      parameters:
      - description: Event Object
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/models.Event'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Event'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Create new event
      tags:
      - events
  /events/:id:
    delete:
      description: Delete an event
      parameters:
      - description: Event id
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Delete event
      tags:
      - events
    get:
      description: Get the one event
      parameters:
      - description: event id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Get particular event by id
      tags:
      - events
    put:
      description: Update event
      parameters:
      - description: Event Object
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/models.Event'
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Update an event
      tags:
      - events
  /events/:id/register:
    delete:
      description: Cancels Registration of an user to the Event
      parameters:
      - description: event id
        in: path
        name: id
        required: true
        type: string
      responses:
        "202":
          description: Accepted
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Cancel Registration for an event
      tags:
      - registration
    post:
      description: Registers an user to the Event
      parameters:
      - description: event id
        in: path
        name: id
        required: true
        type: string
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Register for an event
      tags:
      - registration
  /login:
    post:
      description: Logins an user in the app
      parameters:
      - description: user body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Login for an user
      tags:
      - users
  /signup:
    post:
      description: Registers an user in the app
      parameters:
      - description: user body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Signup for an user
      tags:
      - users
swagger: "2.0"
